require('plugins')
require('options')
require('utils')
require('keybindings')
require('autocomands')
require('ch-easysearh')
require('ch-vimgo')
require('ch-nvtree')
require('ch-gitsign')
require('ch-quickscope')
require('ch-treesitter')
require('ch-gitblame')
require('ch-telescope')
require('ch-indentline')
require('ch-whichkey')
require('ch-floaterm')
require('ch-galaxyline')
--require('ch-lightbulb')
vim.cmd('source $HOME/.config/nvim/vimscripts/vis.vim')
vim.cmd('source $HOME/.config/nvim/vimscripts/functions.vim')
vim.cmd('source $HOME/.config/nvim/vimscripts/misc.vim')
