require('default-config')
vim.cmd('luafile ' .. CONFIG_PATH .. '/ch-config.lua')
require('plugins')
require('options')
require('utils')
require('keybindings')
require('autocomands')
require('ch-gitblame')
require('lsp')
vim.cmd('source $HOME/.config/nvim/vimscripts/vis.vim')
vim.cmd('source $HOME/.config/nvim/vimscripts/functions.vim')
vim.cmd('source $HOME/.config/nvim/vimscripts/misc.vim')
